<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="lidar_height" value="0.077" />
    <xacro:property name="lidar_radius" value="0.039" />

    <!-- Include lidar -->
    <link name="laser_link">
        <visual>
            <geometry>
                <mesh filename="file:///home/thien123/ROS2WS/robocon_ws/install/robot_description/share/robot_description/mesh/sensors/lds.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 ${lidar_height/4}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_height}" length="${lidar_radius}" />
            </geometry>
            <origin xyz="0 0 ${lidar_height/4}" rpy="0 0 0" />
            <material name="grey" />
        </collision>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link" />
        <child link="laser_link" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
    </joint>

</robot> 